# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c78f8941a7cd641fabf4a12646b29682dac34a28093d0943dc1decc9ae0600a17b62f222c3cb1e189cf713b6a4543314334e485643bbe26f3631b2a744a3618

test:
  secret_key_base: 52370a062b6b51e25bcf3517f436b94ef9b261ef3d524607e24706208c191136192c0376e981f38213e4b60de2bcb895d526216f678c48c644b9d57454ff13bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
